export const SongsActionTypes = {
    FETCH_ALL_SONG_START: 'FETCH_ALL_SONG_START',
    FETCH_ALL_SONG_SUCCESS: 'FETCH_ALL_SONG_SUCCESS',
    FETCH_ALL_SONG_FAILURE: 'FETCH_ALL_SONG_FAILURE',
    DISPLAY_BOTTOM_PLAYER: 'DISPLAY_BOTTOM_PLAYER',
    ACTIVATED_SONG_START: "ACTIVATED_SONG_START",
    CHANGE_CURRENT_PAGE_TEXT: "CHANGE_CURRENT_PAGE_TEXT",
    CATALOGUE_HOLDER_START: "CATALOGUE_HOLDER_START",
    SORTED_SEARCH_TEXT_START: "SORTED_SEARCH_TEXT_START",
    PUSH_TO_SELECTED_SONGS: "PUSH_TO_SELECTED_SONGS",
    DISPLAY_ADD_TO_PLAYLIST_PANEL: "DISPLAY_ADD_TO_PLAYLIST_PANEL",
    ACTIVATED_PLAY_OR_PAUSE: "ACTIVATED_PLAY_OR_PAUSE",
    
    POST_SONG_TO_PLAYLIST_START: "POST_SONG_TO_PLAYLIST_START",
    FETCH_SONG_FROM_PLAYLIST_START: "FETCH_SONG_FROM_PLAYLIST_START",
    REMOVE_SONG_FROM_PLAYLIST_START: "REMOVE_SONG_FROM_PLAYLIST_START",
    CREATE_PLAYLIST_START: "CREATE_PLAYLIST_START",
    DELETE_PLAYLIST_START:"DELETE_PLAYLIST_START",
    POST_SONG_TO_PLAYLIST_SUCCESS: "POST_SONG_TO_PLAYLIST_SUCCESS",
    FETCH_SONG_FROM_PLAYLIST_SUCCESS: "FETCH_SONG_FROM_PLAYLIST_SUCCESS",  
    REMOVE_SONG_FROM_PLAYLIST_SUCCESS: "REMOVE_SONG_FROM_PLAYLIST_SUCCESS",
    CREATE_PLAYLIST_SUCCESS: "CREATE_PLAYLIST_SUCCESS",
    DELETE_PLAYLIST_SUCCESS:"DELETE_PLAYLIST_SUCCESS",
    POST_SONG_TO_PLAYLIST_FAILURE: "POST_SONG_TO_PLAYLIST_FAILURE",
    FETCH_SONG_FROM_PLAYLIST_FAILURE: "FETCH_SONG_FROM_PLAYLIST_FAILURE",    
    REMOVE_SONG_FROM_PLAYLIST_FAILURE: "REMOVE_SONG_FROM_PLAYLIST_FAILURE",
    CREATE_PLAYLIST_FAILURE: "CREATE_PLAYLIST_FAILURE",
    DELETE_PLAYLIST_FAILURE:"DELETE_PLAYLIST_FAILURE",
    ACTIVATED_PLAYLIST_START: "ACTIVATED_PLAYLIST_START",
}












// {
//     'version': 2,
//     'builds': [
//         {
//             "src": "NgStore/wsgi.py",
//             "use": "@ardnt/vercel-python-wsgi",
//             "config": {"maxLambdaSize": "15mb", "runtime": "python3.8"}
//         },
//         {
//             "src": "build_files.sh",
//             "use": "@vercel/static-build",
//             "config": {"distDir": "staticfiles_build"}
//         },
//     ],
//     'routes': [
//         {
//             "src": "/static/(.*)",
//             "dest": "/static/$1",
//         },
//         {
//             "src": "/(.*)",
//             "dest": "NgStore/wsgi.py",
//         }
//     ]
// }
